sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: m7u+XoneBm6N+VSt8lkpH9Zi8aZMA7vgg7VZgCc7PiP/N0nbUAeoNHIWv6Hi4mc6xfZYuQ31EHSKt4uM3f710rzR8JuYSd97vVAMronP2vMMw2ziP9jaTehTSLVozChUVsf0D6UsN2CXj/7NEirEXnNkiU7H95GJKMP2b+ptcIVfWc6xnNNvIlChGxOchqdQ6wyi4Genoj7HU+L6GZBSlExUI0lBm9jOtsDuf+sAywZRC2m8S/3Y1njqvu/6vfS6SpBkglhcwHKdKYFDDdSBrY1xkogL3uiDJCPUh2GcsiB/WB4Rkzz1vl1YScD8kcW+HOvwtpzeQhawzBSERO9b4BX2oUqEZZRQOyfZgb7++leofYpTTtHkEgfQMVXSxd0kOpTnVK0ukuHGSsU2SesJPyINJtH7GQgz00c1TgiihNzL8968WLqkz2FRhyIuNZN8C5n2GQLbJkOmVBI3n9qS9vocf14uMkP3SESlJDF3MDhPV2JOKjB0WRE1SZwGS08pTGeG+nC8NnInM2bjJ84aF8FN72wISFlGv2J6uYSCL6mHsX7Oar4Pg21Jck9f3/Zw/fAaKQQcFaAwtajXPI/Cp+sS0Scyq4AIHxbWCtUhQ4mq8cl141pqod2BoPzgpBXvTvFQcHzcm/jnNfeCvfk8QZQBiBBVTM0ARwq/bmPZFMc=
branches:
  only:
  - "/^v\\d.*$/"
  - master
  - development
php:
- 5.6
- 7.1
- 7.2
env:
- WP_VERSION=4.4 WP_MULTISITE=0
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=trunk WP_MULTISITE=0
matrix:
  fast_finish: true
  exclude:
  - php: 7.1
    env: WP_VERSION=4.4 WP_MULTISITE=0
install:
 - nvm install 6 && nvm use 6
 - export DEV_LIB_PATH=.dev/dev-lib
 - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
 - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
 - source $DEV_LIB_PATH/travis.install.sh
script:
- source $DEV_LIB_PATH/travis.script.sh
after_script:
- source $DEV_LIB_PATH/travis.after_script.sh
before_deploy:
- npm install
- grunt build
deploy:
  provider: releases
  api_key:
    secure: hPpen7fwZtgmhfjRBihM6YR3JumgS2k9lMoAISh9kk0pfDHXgaxwwFNuNUt9eJv0224H/+AXpIWPO8RsYjFYwFAnk1rnUo1iElSOl8VUiQFMU0sB7unITI5tAZ94Kn5RyTybi1pGYpUEIJVMM5xqJf59iD4+6ITELzfjWxrLSPujCatt58fGw8Ul3oZHW3shZGeJK3VHIkEyljC2Ezaphu7pcmwfC5Mi7EqxQO8cOIbGPr1A5JA6qcNGnbbsWfkZI2mA2+Huq0ZsCxsn7ry0JJO5AKSHvHiRHj4QXwcdJCZibXXswUGdBD8LkaIC/+CYinBk5JgXvdV/xo/vt2m7FMnLlcKP1W7nLfdFjhy/MumgfrmJdeTQ9pdC8udDsfMWar/stkeaspP369flUp8m2RFmF5ungaivkehtRwYiMFMke7rK7byaj4YJHLJ1wcRcSQcgIV6YN7LciicokuMVumHoZrOuA13QGVAJStdXgRvCF6RfrRPEwqRv1jqzezmNaQhuPzh8VjDtUqSaKJfz5hyWCrPntf6kVKCL4VCYr9H3F681zKiLdS3VLn54f9Od+8QHM4mhca4RkVGbMOBfMNnM4XtfhL/ktuprNNl5HNazGtGeN0rEbTHfFIfz9xORbjy52o2RMYFkQglYOdxMR5u2cG0hJsi281T208J7wwA=
  file_glob: true
  file: build/BR-Staff-*.zip
  on:
    repo: brothman01/BR-Staff
    tags: true
    php: '7.1'
    condition: "$WP_VERSION=trunk"
  skip_cleanup: true
  overwrite: true
